# Generated by Django 5.2.1 on 2025-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Heures de Travail Réelles'),
        ),
    ]
