# Generated by Django 5.1.2 on 2025-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task_actual_hours_worked"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="permis_de_travail",
            field=models.BooleanField(
                default=False, verbose_name="Permis de Travail Requis"
            ),
        ),
    ]
